name: Test and build of Golang Project

on:
  release:
    types: [published]

jobs:
  build:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...

      - name: Login
        env: 
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: 
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Build
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-example:latest .

      - name: Push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-example:latest